# Site settings
title: Danielle Leong | Software Engineer
email: danielle@danielleleong.com
description: > # this means to ignore newlines until "baseurl:"
  Oakland-based software engineer. Passionate about diversity in tech, cheese, motorcycles, dinosaurs, and any combination of the above.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://danielleleong.com" # the base hostname & protocol for your site
twitter_username: tsunamino
github_username:  dmleong
linkedin:  "http://www.linkedin.com/in/danielleleong/"
disqusid: danielleleong

# Build settings
markdown: kramdown

