# Site settings
title: Danielle Leong
email: danielle@danielleleong.com
description: > # this means to ignore newlines until "baseurl:"
  Oakland-based software engineer with a passion for building safer, consensual software.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://danielleleong.com" # the base hostname & protocol for your site
twitter_username: tsunamino
github_username:  dmleong
linkedin:  "http://www.linkedin.com/in/danielleleong/"
disqusid: danielleleong

# Build settings
markdown: kramdown
